# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zEevnXjrtcH30UOzZYqRjpDgy21u26bp
"""

inp = open('/content/input3.txt',"r")
out = open('/content/output3.txt',"w")

x,y = list(map(int,inp.readline().split()))
adjL = [[] for i in range(x+1)] #creating adj list

for i in range(y):
  a,b = list(map(int,inp.readline().split()))
  adjL[a].append(b) #inputing all nodes into adj list
  adjL[b].append(a)


def DFS(G,s):
  out.write(f"{s}") #print the first Vertex
  col = ["w"] * (x+1) #color with initializing White
  def DFS_visit(G,curr):
    col[curr] = "g" #while travarsing GREY
    for v in G[curr]:
      if col[v] == "w": #if white then traverse
        out.write(f" {v}") #traversing and print VERTEX
        DFS_visit(G,v)
    col[curr] = "b" #Traverse end BLACK

  for i in range(1,x+1): #iterate in all vertex
    if col[i] == "w": #if vertex color WHITE call DFS
      DFS_visit(G,i)
DFS(adjL,1)
