# -*- coding: utf-8 -*-
"""task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QGh2fvyTxvILBS2kG-b0rbVNBP5nc5JZ
"""

inp = open('/content/input1b.txt',"r")
out = open('/content/output1b.txt',"w")

x,y = list(map(int,inp.readline().split()))

adjL = []*(x+1)
for i in range(x+1):
  adjL.append([])


for i in range(y):
  a,b,c = list(map(int,inp.readline().split()))
  adjL[a].append((b,c))
print(adjL)
for i in range(x+1):
  out.write(f"{i} :")
  for j in adjL[i]:
    out.write(f" {j} ")
  out.write(f"\n")

inp.close()
out.close()

